runtime: php74

vpc_access_connector:
  name: projects/cs-portal-admin-development/locations/asia-northeast1/connectors/connector01
  egress_setting: all-traffic

runtime_config:
  document_root: ./public

includes:
- .gcp/env.yaml

handlers:
  - url: /css
    static_dir: public/css

  - url: /images
    static_dir: public/images

  - url: /js
    static_dir: public/js

  - url: /robots.txt
    static_files: public/robots.txt
    upload: public/robots\.txt

  - url: .*
    script: auto
