# CircleCI configuration

version: 2.1

executors:
  my_executor:
    docker:
      - image: circleci/php:7.2

jobs:
  build_development:
    working_directory: ~/development
    executor: my_executor

    steps:
      - checkout

      - restore_cache:
          keys:
            - composer-dev-{{ checksum "composer.lock" }}
            - composer-

      - run:
          name: Composer install (with require-dev)
          command: composer install --dev -n --prefer-dist

      - save_cache:
          key: composer-dev-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      - run:
          name: ZIP archive
          command: zip -r development_app.zip . -x \*.git\* \*.circleci\* \*analysis\* \*docker\* \*report\* .gitignore composer.\* docker-compose.yml phpcs.xml phpstan.neon .editorconfig \*.env \*.user.ini public/sample.htaccess public/sample.Web.config

      - store_artifacts:
          path: ./development_app.zip

      - persist_to_workspace:
          root: .
          paths:
            - .

  build_production:
    working_directory: ~/production
    executor: my_executor

    steps:
      - checkout

      - restore_cache:
          keys:
            - composer-{{ checksum "composer.lock" }}
            - composer-

      - run:
          name: Composer install
          command: composer install --no-dev -n --prefer-dist --optimize-autoloader

      - save_cache:
          key: composer-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      - run:
          name: Create .env file
          command: echo $CI_DOTENV | base64 --decode > .env

      - run:
          name: Generate ORM proxies
          command: vendor/bin/doctrine orm:generate-proxies

      - run:
          name: Remove .env file
          command: rm -v ./.env

      - run:
          name: ZIP archive
          command: zip -r production_app.zip . -x \*.git\* \*.circleci\* \*analysis\* \*docker\* \*report\* .gitignore composer.\* docker-compose.yml phpcs.xml phpstan.neon .editorconfig \*.env \*.user.ini public/sample.htaccess public/sample.Web.config

      - store_artifacts:
          path: ./production_app.zip

      - persist_to_workspace:
          root: .
          paths:
            - .

  analysis:
    working_directory: ~/development
    executor: my_executor

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Create .env file
          command: echo $CI_DOTENV | base64 --decode > .env

      # 確認用
      # - store_artifacts:
      #     path: ./.env

      - run:
          name: PHP CodeSniffer
          command: composer phpcs

      - run:
          name: PHPStan
          command: composer phpstan > ./report/phpstan_result.txt

      - store_artifacts:
          path: ./report

      - run:
          name: Remove .env file
          command: rm -v ./.env

  deploy_to_dev:
    working_directory: ~/development
    executor: my_executor
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Deploy to Azure
          command: curl -X POST https://$DEV_AAS_USER:$DEV_AAS_PASSWORD@ssk-portal2018-admin-win-dev.scm.azurewebsites.net/api/zipdeploy -T development_app.zip

  deploy_to_test:
    working_directory: ~/development
    executor: my_executor
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Deploy to Azure
          command: curl -X POST https://$TEST_AAS_USER:$TEST_AAS_PASSWORD@ssk-portal2018-admin-win-test.scm.azurewebsites.net/api/zipdeploy -T development_app.zip

  deploy_to_prod:
    working_directory: ~/production
    executor: my_executor

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Deploy to Azure
          command: curl -X POST https://$PROD_AAS_USER:$PROD_AAS_PASSWORD@ssk-portal2018-admin-win-prod.scm.azurewebsites.net/api/zipdeploy -T production_app.zip

workflows:
  version: 2

  deploy_development:
    jobs:
      - build_development:
          filters:
            branches:
              only: develop

      - analysis:
          requires:
            - build_development

      - deploy_to_dev:
          requires:
            - build_development

  deploy_development_feature:
    jobs:
      - build_development:
          filters:
            branches:
              ignore:
                - develop
                - master

      - analysis:
          requires:
            - build_development

      - deploy_approval:
          type: approval
          requires:
            - build_development

      - deploy_to_test:
          requires:
            - deploy_approval

  deploy_production:
    jobs:
    - build_development:
        filters:
          branches:
            only: master

    - analysis:
        requires:
          - build_development

    - build_production:
        requires:
          - analysis

    - deploy_approval:
        type: approval
        requires:
          - build_production

    - deploy_to_prod:
        requires:
          - deploy_approval
